spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: Kakao-client-id
            client-secret: Kakao-client-secret
            redirect-uri: http://localhost:8080/api/login/oauth2/kakao
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao
          google:
            client-id: google-client-id
            client-secret: google-client-secret
            redirect-uri: http://localhost:8080/api/login/oauth2/google
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
            client-name: google
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
jwt:
  secret: secret-key
refresh:
  secret: secret-key2