spring:
  application:
    name: illuwabang

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/illuwabang
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  profiles:
    include: oauth

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace
